module.exports = [
  "about_sections",
  "academic_terms",
  "activities",
  "ai_tutor_logs",
  "announcements",
  "announcement_views",
  "assignment_submission_guides",
  "assignment_submissions",
  "attendance_records",
  "attendance_sessions",
  "benefits",
  // "candidates" and "votes" exist in the DB but aren't created by
  // models/initTables.js and aren't referenced anywhere in the app code
  // — orphaned/legacy, not part of any current feature. Included here
  // anyway per an explicit request to expose every table that exists,
  // not just ones the app actively uses.
  "candidates",
  "career_pathways",
  "categories",
  "class_messages",
  "class_term_reports",
  "classroom_courses",
  "classroom_instructors",
  "classroom_teachers",
  "classrooms",
  "company_info",
  "course_enrollments",
  "course_projects",
  "course_term_links",
  "courses",
  "event_registrations",
  "events",
  "faqs",
  "feedback",
  "gallery_categories",
  "gallery_images",
  "invoice_students",
  "lab_projects",
  "lab_submissions",
  "learning_guides",
  "lesson_assignments",
  "lesson_labs",
  "lessons",
  "messages",
  "module_assignments",
  "modules",
  "muted_students",
  "newsletters",
  "newsletter_recipients",
  "parent_child_requests",
  "parent_children",
  "parent_payments",
  "parent_training_invoices",
  "pending_users",
  "playground_projects",
  "project_submissions",
  "push_subscriptions",
  "quiz_questions",
  "quiz_submissions",
  "quizzes",
  "quotes",
  "report_generation_log",
  "school_courses",
  "school_payment_adjustments",
  "school_payments",
  "schools",
  "student_badges",
  "student_term_enrollments",
  "student_term_reactivations",
  "student_xp",
  "students",
  "subscriptions",
  "testimonies",
  "transactions",
  "unlocked_assignments",
  "unlocked_lessons",
  "unlocked_modules",
  "user_badges",
  "user_certificates",
  "user_lesson_progress",
  "user_school",
  // Legacy/orphaned like "candidates"/"votes" above — no app code
  // reads or writes a table literally named "users" anywhere; the real
  // users table is "users2". Included for completeness, not because
  // it's in active use.
  "users",
  "users2",
  "votes",
  "xp_history",

  // add more gradually
];